"""
This script generates a .env.example file by statically analyzing the entire
codebase for environment variable usage.

It walks through all Python files in the 'src' directory, parses them into an
Abstract Syntax Tree (AST), and identifies all calls to `os.getenv()` and
`os.environ.get()`. It extracts the variable names and their default values.

This approach ensures that the .env.example file stays up-to-date with the
actual environment variables used in the code.

Additionally, it maintains a small list of variables for third-party libraries
that may not be explicitly accessed via `os.getenv` in our codebase.
"""

import ast
import os
from pathlib import Path

# --- Configuration ---
SRC_DIRECTORY = "src"
THIRD_PARTY_VARS = {
    "REDIS": {
        "REDIS_HOST": "localhost",
        "REDIS_PORT": "6379",
        "REDIS_PASSWORD": "",
    },
    "LITELLM": {
        "LITELLM_PROXY_URL": "http://0.0.0.0:8000",
        "LITELLM_API_KEY": "your_litellm_api_key",
        "GEMINI_API_KEY": "your_gemini_api_key",
    },
}


class EnvVarVisitor(ast.NodeVisitor):
    """AST visitor to find environment variable calls."""

    def __init__(self):
        self.env_vars = {}

    def visit_Call(self, node):
        # Look for os.getenv("VAR", "default") or os.environ.get("VAR", "default")
        if isinstance(node.func, ast.Attribute) and isinstance(
            node.func.value, (ast.Name, ast.Attribute)
        ):
            # Check for os.getenv or os.environ.get
            func_name = node.func.attr
            module_name = ""
            if isinstance(node.func.value, ast.Name) and node.func.value.id == "os":
                module_name = "os"
            elif (
                isinstance(node.func.value, ast.Attribute)
                and node.func.value.attr == "environ"
            ):
                module_name = "os.environ"

            if (
                module_name in ["os", "os.environ"]
                and func_name in ["getenv", "get"]
                and node.args
            ):
                var_name_node = node.args[0]
                if isinstance(var_name_node, ast.Constant):
                    var_name = var_name_node.value
                    default_value = ""
                    if len(node.args) > 1:
                        default_value_node = node.args[1]
                        if isinstance(default_value_node, ast.Constant):
                            default_value = default_value_node.value
                    self.env_vars[var_name] = str(default_value)

        self.generic_visit(node)


def scan_codebase_for_env_vars(directory: str) -> dict:
    """Scans all Python files in a directory for env var usage."""
    visitor = EnvVarVisitor()
    for root, _, files in os.walk(directory):
        for file in files:
            if file.endswith(".py"):
                file_path = Path(root) / file
                with open(file_path, "r", encoding="utf-8") as f:
                    try:
                        tree = ast.parse(f.read(), filename=str(file_path))
                        visitor.visit(tree)
                    except SyntaxError as e:
                        print(f"Warning: Could not parse {file_path}. Error: {e}")
    return visitor.env_vars


def generate_env_example():
    """
    Generates the .env.example file.
    """
    project_root = Path(__file__).resolve().parent.parent.parent
    env_example_path = project_root / ".env.example"

    print(f"Scanning for environment variables in '{SRC_DIRECTORY}'...")
    scanned_vars = scan_codebase_for_env_vars(str(project_root / SRC_DIRECTORY))

    # Combine scanned variables with third-party, avoiding duplicates
    combined_vars = scanned_vars.copy()
    for group, variables in THIRD_PARTY_VARS.items():
        for name, default in variables.items():
            if name not in combined_vars:
                combined_vars[name] = default

    with open(env_example_path, "w", encoding="utf-8") as f:
        f.write(
            "# This file was auto-generated by src/scripts/generate_env_example.py\n"
        )
        f.write(
            "# It contains environment variables discovered by scanning the codebase.\n\n"
        )

        f.write(
            "# It contains environment variables discovered by scanning the codebase.\n\n"
        )

        f.write("# --- Discovered Settings ---\n")
        # Sort variables for consistent output
        for env_name, default_value in sorted(combined_vars.items()):
            f.write(f"{env_name}={default_value}\n")
        f.write("\n")

    print(f"Successfully generated {env_example_path}")
    print(f"Discovered {len(scanned_vars)} application-specific variables.")


if __name__ == "__main__":
    generate_env_example()
