model_list:
  - model_name: gemini-synthesis-model
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY_1
      rpm: 9
      tpm: 225000
      stream: false
  - model_name: gemini-synthesis-model
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY_2
      rpm: 9
      tpm: 225000
      stream: false
  - model_name: gemini-synthesis-model
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY_3
      rpm: 9
      tpm: 225000
      stream: false
  - model_name: gemini-synthesis-model
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY_4
      rpm: 9
      tpm: 225000
      stream: false
  - model_name: gemini-synthesis-model
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY_5
      rpm: 9
      tpm: 225000
      stream: false
  - model_name: gemini-synthesis-model
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY_6
      rpm: 9
      tpm: 225000
      stream: false
  - model_name: gemini-synthesis-model
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY_7
      rpm: 9
      tpm: 225000
      stream: false
  - model_name: gemini-synthesis-model
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY_8
      rpm: 9
      tpm: 225000
      stream: false
  - model_name: gemini-synthesis-model
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY_9
      rpm: 9
      tpm: 225000
      stream: false
  - model_name: gemini-synthesis-model
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY_10
      rpm: 9
      tpm: 225000
      stream: false
  - model_name: gemini-synthesis-model
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY_11
      rpm: 9
      tpm: 225000
      stream: false
  - model_name: gemini-synthesis-model
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY_12
      rpm: 9
      tpm: 225000
      stream: false

  - model_name: gemini-embedding-model
    litellm_params:
      model: gemini/gemini-embedding-001
      api_key: os.environ/GEMINI_API_KEY_1
      output_dimensionality: 768
  - model_name: gemini-embedding-model
    litellm_params:
      model: gemini/gemini-embedding-001
      api_key: os.environ/GEMINI_API_KEY_2
      output_dimensionality: 768
  - model_name: gemini-embedding-model
    litellm_params:
      model: gemini/gemini-embedding-001
      api_key: os.environ/GEMINI_API_KEY_3
      output_dimensionality: 768
  - model_name: gemini-embedding-model
    litellm_params:
      model: gemini/gemini-embedding-001
      api_key: os.environ/GEMINI_API_KEY_4
      output_dimensionality: 768
  - model_name: gemini-embedding-model
    litellm_params:
      model: gemini/gemini-embedding-001
      api_key: os.environ/GEMINI_API_KEY_5
      output_dimensionality: 768
  - model_name: gemini-embedding-model
    litellm_params:
      model: gemini/gemini-embedding-001
      api_key: os.environ/GEMINI_API_KEY_6
      output_dimensionality: 768
  - model_name: gemini-embedding-model
    litellm_params:
      model: gemini/gemini-embedding-001
      api_key: os.environ/GEMINI_API_KEY_7
      output_dimensionality: 768
  - model_name: gemini-embedding-model
    litellm_params:
      model: gemini/gemini-embedding-001
      api_key: os.environ/GEMINI_API_KEY_8
      output_dimensionality: 768
  - model_name: gemini-embedding-model
    litellm_params:
      model: gemini/gemini-embedding-001
      api_key: os.environ/GEMINI_API_KEY_9
      output_dimensionality: 768
  - model_name: gemini-embedding-model
    litellm_params:
      model: gemini/gemini-embedding-001
      api_key: os.environ/GEMINI_API_KEY_10
      output_dimensionality: 768

router_settings:
  # routing_strategy: "rate-limit-aware-v2"
  routing_strategy: usage-based-routing-v2
  cache_responses: true
  cache_kwargs:
    type: "redis"
    host: os.environ/REDIS_HOST
    port: os.environ/REDIS_PORT
    password: os.environ/REDIS_PASSWORD
    ttl: 3600

# general_settings:
#   pass_raw_headers: true

litellm_settings:
  drop_params: true
  turn_off_message_logging: true
  set_verbose: false
