# This is a basic workflow to help you get started with Actions.
# For more information about GitHub Actions, see:
# https://docs.github.com/en/actions

name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Check formatting with Ruff
        run: |
          ruff format --check .

      - name: Lint with Ruff
        run: |
          ruff check .

      - name: Test with pytest
        run: |
          pytest
