name: Lint & Preflight

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt || true
      - name: Run black check
        run: black --check .
      - name: Run isort check
        run: isort --check-only .
      - name: Run flake8
        run: flake8 .

  preflight:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt
      - name: Run litellm preflight
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python3 src/scripts/check_litellm_setup.py || true
